server.port : 8080

spring.datasource.url : "jdbc:mysql://localhost:3306/taskproject"
# after port, he gave schema name

spring.datasource.username : root
spring.datasource.password : "#InsanityHumanity1"
spring.datasource.driver-class-name : com.mysql.cj.jdbc.Driver
spring.jpa.show-sql : true
spring.jpa.hibernate.ddl-auto : update
#  changes made in Entities. (Lets say we added new constraint in Entities) will reflect in mysql DB.
